import {
  LayoutDashboard,
  Receipt,
  Settings,
  ShieldCheck,
  Store as StoreIcon,
  Users,
} from "lucide-react";
import type {
  User,
  Vendor,
  Store,
  Order,
  Page,
  Conversation,
} from "./types/admin";

export const USERS: User[] = [
  {
    id: "u1",
    name: "Amaka Osei",
    email: "amaka@email.com",
    role: "Buyer",
    status: "active",
    initials: "AO",
    joined: "May 18, 2026",
    orders: 14,
    spent: 142000,
  },
  {
    id: "u2",
    name: "Babatunde Makinde",
    email: "bm@email.com",
    role: "Buyer",
    status: "pending",
    initials: "BM",
    joined: "May 17, 2026",
    orders: 0,
    spent: 0,
  },
  {
    id: "u3",
    name: "Chisom Nwosu",
    email: "chisom@email.com",
    role: "Admin",
    status: "active",
    initials: "CN",
    joined: "May 16, 2026",
    orders: 3,
    spent: 28500,
  },
  {
    id: "u4",
    name: "David Kamau",
    email: "dk@email.com",
    role: "Buyer",
    status: "suspended",
    initials: "DK",
    joined: "Apr 2, 2026",
    orders: 7,
    spent: 65000,
  },
  {
    id: "u5",
    name: "Emeka Fashola",
    email: "emeka@email.com",
    role: "Vendor",
    status: "active",
    initials: "EF",
    joined: "Mar 11, 2026",
    orders: 0,
    spent: 0,
  },
  {
    id: "u6",
    name: "Fatimah Bello",
    email: "fatimah@email.com",
    role: "Buyer",
    status: "active",
    initials: "FB",
    joined: "Mar 5, 2026",
    orders: 22,
    spent: 198000,
  },
  {
    id: "u7",
    name: "Grace Adekunle",
    email: "grace@email.com",
    role: "Buyer",
    status: "active",
    initials: "GA",
    joined: "Feb 20, 2026",
    orders: 9,
    spent: 87500,
  },
  {
    id: "u8",
    name: "Hassan Musa",
    email: "hassan@email.com",
    role: "Vendor",
    status: "pending",
    initials: "HM",
    joined: "May 19, 2026",
    orders: 0,
    spent: 0,
  },
  {
    id: "u9",
    name: "Ifeoma Chukwu",
    email: "ife@email.com",
    role: "Buyer",
    status: "active",
    initials: "IC",
    joined: "Jan 15, 2026",
    orders: 31,
    spent: 312000,
  },
  {
    id: "u10",
    name: "James Okafor",
    email: "james@email.com",
    role: "Buyer",
    status: "banned",
    initials: "JO",
    joined: "Dec 10, 2025",
    orders: 2,
    spent: 12000,
  },
];

export const VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "Kente Styles Ltd",
    email: "hello@kentestyles.com",
    category: "Fashion",
    status: "verified",
    stores: 4,
    revenue: 2400000,
    initials: "KS",
    joined: "Nov 1, 2025",
    rating: 4.8,
  },
  {
    id: "v2",
    name: "SpiceHub Lagos",
    email: "info@spicehub.ng",
    category: "Food & Grocery",
    status: "pending",
    stores: 1,
    revenue: 0,
    initials: "SH",
    joined: "May 15, 2026",
    rating: 0,
  },
  {
    id: "v3",
    name: "TechGadgets NG",
    email: "sales@techgadgets.ng",
    category: "Electronics",
    status: "verified",
    stores: 2,
    revenue: 5100000,
    initials: "TG",
    joined: "Sep 22, 2025",
    rating: 4.6,
  },
  {
    id: "v4",
    name: "Beauté Femme",
    email: "hello@beautefemme.ng",
    category: "Beauty",
    status: "verified",
    stores: 3,
    revenue: 1800000,
    initials: "BF",
    joined: "Jan 8, 2026",
    rating: 4.9,
  },
  {
    id: "v5",
    name: "FurnitureCo Lagos",
    email: "orders@furniturecо.ng",
    category: "Home & Living",
    status: "suspended",
    stores: 1,
    revenue: 890000,
    initials: "FC",
    joined: "Aug 14, 2025",
    rating: 3.2,
  },
  {
    id: "v6",
    name: "AutoParts Direct",
    email: "info@autoparts.ng",
    category: "Automotive",
    status: "rejected",
    stores: 0,
    revenue: 0,
    initials: "AP",
    joined: "May 19, 2026",
    rating: 0,
  },
];

export const STORES: Store[] = [
  {
    id: "s1",
    name: "Kente Flagship",
    vendor: "Kente Styles Ltd",
    location: "Victoria Island, Lagos",
    products: 142,
    status: "active",
    revenue: 980000,
    created: "Nov 15, 2025",
    rating: 4.9,
  },
  {
    id: "s2",
    name: "Gadgets Central",
    vendor: "TechGadgets NG",
    location: "Ikeja, Lagos",
    products: 89,
    status: "active",
    revenue: 2100000,
    created: "Oct 1, 2025",
    rating: 4.7,
  },
  {
    id: "s3",
    name: "SpiceHub Surulere",
    vendor: "SpiceHub Lagos",
    location: "Surulere, Lagos",
    products: 23,
    status: "pending",
    revenue: 0,
    created: "May 16, 2026",
    rating: 0,
  },
  {
    id: "s4",
    name: "Beauté VI",
    vendor: "Beauté Femme",
    location: "Lekki Phase 1, Lagos",
    products: 67,
    status: "active",
    revenue: 540000,
    created: "Jan 20, 2026",
    rating: 4.8,
  },
  {
    id: "s5",
    name: "Kente Abuja",
    vendor: "Kente Styles Ltd",
    location: "Wuse II, Abuja",
    products: 98,
    status: "active",
    revenue: 720000,
    created: "Feb 10, 2026",
    rating: 4.6,
  },
  {
    id: "s6",
    name: "FurnitureCo Showroom",
    vendor: "FurnitureCo Lagos",
    location: "Yaba, Lagos",
    products: 54,
    status: "inactive",
    revenue: 890000,
    created: "Aug 20, 2025",
    rating: 3.2,
  },
];

export const ORDERS: Order[] = [
  {
    id: "BNC-8821",
    customer: "Amaka Osei",
    store: "Kente Flagship",
    vendor: "Kente Styles Ltd",
    amount: 14500,
    status: "delivered",
    items: 2,
    date: "May 19, 2026",
  },
  {
    id: "BNC-8820",
    customer: "Emeka Fashola",
    store: "Gadgets Central",
    vendor: "TechGadgets NG",
    amount: 89000,
    status: "processing",
    items: 1,
    date: "May 19, 2026",
  },
  {
    id: "BNC-8819",
    customer: "Chisom Nwosu",
    store: "Beauté VI",
    vendor: "Beauté Femme",
    amount: 6200,
    status: "delivered",
    items: 3,
    date: "May 18, 2026",
  },
  {
    id: "BNC-8818",
    customer: "Babatunde Makinde",
    store: "Gadgets Central",
    vendor: "TechGadgets NG",
    amount: 120000,
    status: "cancelled",
    items: 1,
    date: "May 18, 2026",
  },
  {
    id: "BNC-8817",
    customer: "Fatimah Bello",
    store: "Kente Flagship",
    vendor: "Kente Styles Ltd",
    amount: 32000,
    status: "shipped",
    items: 4,
    date: "May 17, 2026",
  },
  {
    id: "BNC-8816",
    customer: "Ifeoma Chukwu",
    store: "Kente Abuja",
    vendor: "Kente Styles Ltd",
    amount: 18500,
    status: "delivered",
    items: 2,
    date: "May 17, 2026",
  },
  {
    id: "BNC-8815",
    customer: "Grace Adekunle",
    store: "Beauté VI",
    vendor: "Beauté Femme",
    amount: 9800,
    status: "refunded",
    items: 1,
    date: "May 16, 2026",
  },
  {
    id: "BNC-8814",
    customer: "Amaka Osei",
    store: "Gadgets Central",
    vendor: "TechGadgets NG",
    amount: 55000,
    status: "delivered",
    items: 1,
    date: "May 15, 2026",
  },
];

export const NAV = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "users", label: "Users", icon: Users },
  { id: "vendors", label: "Vendors", icon: ShieldCheck },
  { id: "stores", label: "Stores", icon: StoreIcon },
  { id: "orders", label: "Orders", icon: Receipt },
  { id: "settings", label: "Settings", icon: Settings },
] as const;

export const PAGE_TITLES: Record<Page, string> = {
  overview: "Dashboard",
  users: "Users",
  vendors: "Vendors",
  stores: "Stores",
  orders: "Orders",
  settings: "Settings",
};

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "1",
    user: {
      id: "u1",
      name: "Ade Okafor",
      email: "ade@example.com",
      joinedAt: "Jan 2025",
      initials: "AO",
      avatarColor: "bg-purple-100 text-purple-800",
    },
    messages: [
      {
        id: "m1",
        content:
          "👋 Welcome to the platform, Ade! Let us know if you have any questions.",
        sentAt: new Date(Date.now() - 7200000).toISOString(),
        type: "system",
      },
      {
        id: "m2",
        content:
          "Hi Ade, your account has been verified successfully. You now have full access.",
        sentAt: new Date(Date.now() - 3600000).toISOString(),
        type: "admin",
      },
      {
        id: "m3",
        content:
          "Reminder: please complete your profile to unlock all features.",
        sentAt: new Date(Date.now() - 120000).toISOString(),
        type: "admin",
      },
    ],
    lastMessageAt: new Date(Date.now() - 120000).toISOString(),
    unread: false,
  },
  {
    id: "2",
    user: {
      id: "u2",
      name: "Fatima Malik",
      email: "fatima@example.com",
      joinedAt: "Mar 2025",
      initials: "FM",
      avatarColor: "bg-emerald-100 text-emerald-800",
    },
    messages: [
      {
        id: "m4",
        content:
          "We noticed unusual activity on your account. Please review your recent logins.",
        sentAt: new Date(Date.now() - 3600000).toISOString(),
        type: "admin",
      },
    ],
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    unread: true,
  },
  {
    id: "3",
    user: {
      id: "u3",
      name: "Kofi Entsie",
      email: "kofi@example.com",
      joinedAt: "Feb 2025",
      initials: "KE",
      avatarColor: "bg-orange-100 text-orange-800",
    },
    messages: [
      {
        id: "m5",
        content: "Welcome to the platform!",
        sentAt: new Date(Date.now() - 10800000).toISOString(),
        type: "system",
      },
    ],
    lastMessageAt: new Date(Date.now() - 10800000).toISOString(),
    unread: false,
  },
  {
    id: "4",
    user: {
      id: "u4",
      name: "Ngozi Bello",
      email: "ngozi@example.com",
      joinedAt: "Dec 2024",
      initials: "NB",
      avatarColor: "bg-pink-100 text-pink-800",
    },
    messages: [
      {
        id: "m6",
        content: "Your subscription has renewed successfully.",
        sentAt: new Date(Date.now() - 86400000).toISOString(),
        type: "admin",
      },
    ],
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    unread: false,
  },
  {
    id: "5",
    user: {
      id: "u5",
      name: "Tunde James",
      email: "tunde@example.com",
      joinedAt: "Apr 2025",
      initials: "TJ",
      avatarColor: "bg-blue-100 text-blue-800",
    },
    messages: [
      {
        id: "m7",
        content:
          "Action required on your account — please verify your email address.",
        sentAt: new Date(Date.now() - 172800000).toISOString(),
        type: "admin",
      },
    ],
    lastMessageAt: new Date(Date.now() - 172800000).toISOString(),
    unread: true,
  },
];
